
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace LawFirm.DAL.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Blog
{

    public Blog()
    {

        this.Comments = new HashSet<Comment>();

        this.Paragraphs = new HashSet<Paragraph>();

    }


    public int id { get; set; }

    public string title { get; set; }

    public System.DateTime blogDate { get; set; }

    public string postedby { get; set; }

    public string category { get; set; }

    public string image { get; set; }



    public virtual ICollection<Comment> Comments { get; set; }

    public virtual ICollection<Paragraph> Paragraphs { get; set; }

}

}
