
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace LawFirm.DAL.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Career
{

    public int id { get; set; }

    public string jobTitle { get; set; }

    public string location { get; set; }

    public string postDate { get; set; }

    public string jobType { get; set; }

}

}
