
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace LawFirm.DAL.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Comment
{

    public int id { get; set; }

    public string commentBody { get; set; }

    public string commenterName { get; set; }

    public string commenterEmail { get; set; }

    public int blogId { get; set; }



    public virtual Blog Blog { get; set; }

}

}
