//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LawFirm.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Experience
    {
        public int id { get; set; }
        public string name { get; set; }
        public string val { get; set; }
        public int expertId { get; set; }
    
        public virtual Expert Expert { get; set; }
    }
}
