
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace LawFirm.DAL.Models
{

using System;
    using System.Collections.Generic;
    
public partial class user
{

    public user()
    {

        this.isactive = false;

        this.isonline = false;

    }


    public System.Guid id { get; set; }

    public string username { get; set; }

    public string password { get; set; }

    public string email { get; set; }

    public bool isactive { get; set; }

    public bool isonline { get; set; }

}

}
